export const taskIcons = [
    {id: 'job', label: 'Job'},
    {id: 'doctor_appointment', label: 'Doctor appointment'},
    {id: 'mechanic', label: 'Mechanic'},
    {id: 'electrician', label: 'Electrician'},
    {id: 'transport', label: 'Transport'},
    {id: 'cleaning', label: 'Cleaning'},
    {id: 'swimming', label: 'Swimming'},
    {id: 'gym', label: 'Gym'},
    {id: 'basketball', label: 'Basketball'},
    {id: 'football', label: 'Football'},
    {id: 'american_football', label: 'American football'},
    {id: 'volleyball', label: 'Volleyball'},
    {id: 'concert', label: 'Music concert'},
    {id: 'movie', label: 'Movie'},
    {id: 'meeting', label: 'Meeting'},
    {id: 'reading', label: 'Reading'},
    {id: 'writing', label: 'Writing'},
    {id: 'payment', label: 'Payment'},
    {id: 'message', label: 'Message'},
    {id: 'photography', label: 'Photography'},
    {id: 'moving', label: 'Moving'},
    {id: 'running', label: 'Running'},
    {id: 'drive', label: 'Drive'},
    {id: 'shopping', label: 'Shopping'},
    {id: 'coffee', label: 'Coffee'},
    {id: 'sailing', label: 'Sailing'},
    {id: 'church', label: 'Church'},
    {id: 'pets', label: 'Pets'},
    {id: 'plants', label: 'Plants'},
    {id: 'lunch', label: 'Lunch'},
    {id: 'phone_call', label: 'Phone call'},
    {id: 'computer', label: 'Computer'},
    {id: 'party', label: 'Party'}
];

export const months = [
    {value: 1, label: 'January'},
    {value: 2, label: 'February'},
    {value: 3, label: 'March'},
    {value: 4, label: 'April'},
    {value: 5, label: 'May'},
    {value: 6, label: 'June'},
    {value: 7, label: 'July'},
    {value: 8, label: 'August'},
    {value: 9, label: 'September'},
    {value: 10, label: 'October'},
    {value: 11, label: 'November'},
    {value: 12, label: 'December'}
];