export const taskIcons = [
    {id: 'job', label: 'Job'},
    {id: 'doctor_appointment', label: 'Doctor appointment'},
    {id: 'mechanic', label: 'Mechanic'},
    {id: 'electrician', label: 'Electrician'},
    {id: 'transport', label: 'Transport'},
    {id: 'cleaning', label: 'Cleaning'},
    {id: 'swimming', label: 'Swimming'},
    {id: 'gym', label: 'Gym'},
    {id: 'basketball', label: 'Basketball'},
    {id: 'football', label: 'Football'},
    {id: 'american_football', label: 'American football'},
    {id: 'volleyball', label: 'Volleyball'},
    {id: 'concert', label: 'Music concert'},
    {id: 'movie', label: 'Movie'},
    {id: 'meeting', label: 'Meeting'},
    {id: 'reading', label: 'Reading'},
    {id: 'writing', label: 'Writing'},
    {id: 'payment', label: 'Payment'},
    {id: 'message', label: 'Message'},
    {id: 'photography', label: 'Photography'},
    {id: 'moving', label: 'Moving'},
    {id: 'running', label: 'Running'},
    {id: 'drive', label: 'Drive'},
    {id: 'shopping', label: 'Shopping'},
    {id: 'coffee', label: 'Coffee'},
    {id: 'sailing', label: 'Sailing'},
    {id: 'church', label: 'Church'},
    {id: 'pets', label: 'Pets'},
    {id: 'plants', label: 'Plants'},
    {id: 'lunch', label: 'Lunch'},
    {id: 'phone_call', label: 'Phone call'},
    {id: 'computer', label: 'Computer'},
    {id: 'party', label: 'Party'}
];

export const months = [
    {value: '01', label: 'January'},
    {value: '02', label: 'February'},
    {value: '03', label: 'March'},
    {value: '04', label: 'April'},
    {value: '05', label: 'May'},
    {value: '06', label: 'June'},
    {value: '07', label: 'July'},
    {value: '08', label: 'August'},
    {value: '09', label: 'September'},
    {value: '10', label: 'October'},
    {value: '11', label: 'November'},
    {value: '12', label: 'December'}
];